config/routes.rb
Biblioteka::Application.routes.draw do
  root "books#index"
  resources :books
  devise_for :librarians
  devise_for :readers
  resources :receipts
  resources :readers

  

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :authors_books
  has_and_belongs_to_many :books
end

app/models/authors_books.rb
class AuthorsBooks < ActiveRecord::Base
  belongs_to :book
  belongs_to :author
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :authors_books
  has_and_belongs_to_many :authors

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :default_url => "/images/:style/missing.png"
  validates_attachment_presence :avatar
end

app/models/librarian.rb
class Librarian < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :receipt
end

app/models/penalty.rb
class Penalty < ActiveRecord::Base
has_many :receipt
end

app/models/reader.rb
class Reader < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :receipts
  has_many :penalties, :through => :receipts
  has_many :books, :through => :receipts
  validates :name, :surname, :birth_date, :email, presence: true
end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  belongs_to :reader
  belongs_to :penalty
  belongs_to :librarian
  belongs_to :book

  validates_presence_of :book
  validates_presence_of :reader

  NEW = 1
  READER_CANCELED = 2
  ACTIVE = 3
  LIBRARIAN_CANCELED = 4
  READY = 5
  SHIPPED = 6
  RETURNED = 7
  CANCELED_ACTIVE = 8

  STATUSES = [NEW, READER_CANCELED, ACTIVE, LIBRARIAN_CANCELED, READY, SHIPPED, RETURNED, CANCELED_ACTIVE]

  validates_inclusion_of :status, :in => STATUSES

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :surname, :birth_date, :email, :password, :password_confirmation) }
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :librarian_signed_in?, only: [:new, :create, :edit, :update, :destroy]

  def index
    #@books = Book.all
    @books = Book.order("updated_at DESC").paginate(:page => params[:page], :per_page => 10)
  end

  def new
     @book = Book.new


  end

  def create
    @book = Book.new(book_params)
    #@book.image = params[:book]
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was succesfuly created.' }
        format.json { render action: 'index', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
      @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    respond_to do |format|
      format.html { redirect_to(books_url) }
      format.json { head :no_content }
    end
  end

  def book_params
    params.require(:book).permit(:title, :release_date, :author_id, :avatar)
  end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  def index
    @receipts = Receipt.order("updated_at DESC").paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @receipt = current_reader.receipts.find(params[:id])
  end

  def new
  end

  def create
    @receipt = current_reader.receipts.build(receipt_params)
    @receipt.status = Receipt::NEW
    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: 'Receipt was succesfuly created.' }
        format.json { render action: 'index', status: :created, location: @book }
      else
        format.html { redirect_to books_path, alert: "Nie udało się dodać książki do zamówień" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit

  end

  def update
    @receipt = Receipt.find params[:id]
    @status = @receipt.status

    if params[:reader_canceled] && @receipt.reader == current_reader && @status == Receipt::NEW
      @receipt.status = Receipt::READER_CANCELED
    end

    if params[:cancel_active] && @receipt.reader == current_reader && (@status == Receipt::ACTIVE || @status == Receipt::READY )
      @receipt.status = Receipt::DELETED_ACTIVE
    end

    if @receipt.librarian == nil
      if params[:accepted] && @status == Receipt::NEW
        @receipt.librarian = current_librarian
        @receipt.status = Receipt::ACTIVE
      end
    end

    if params[:librarian_canceled] && @receipt.librarian == current_librarian && (@status == Receipt::NEW || @status == Receipt::ACTIVE || @status == Receipt::READY)
      @receipt.status = Receipt::LIBRARIAN_CANCELED
    end

    if params[:ready] && @receipt.librarian == current_librarian && @status == Receipt::ACTIVE
      @receipt.status = Receipt::READY
    end

    if params[:shipped] && @receipt.librarian == current_librarian && @status == Receipt::READY
      @receipt.status = Receipt::SHIPPED
    end

    if params[:returned] && @receipt.librarian == current_librarian && @status == Receipt::SHIPPED
      @receipt.status = Receipt::RETURNED
    end
    if @receipt.librarian == current_librarian

    end



    @receipt.save!
    redirect_to receipts_path
  end

  def destroy

  end

  def receipt_params
    params.require(:receipt).permit(:book_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/readers_helper.rb
module ReadersHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper

  def status_for(receipt)
    case receipt.status
    when Receipt::NEW
      "New"
    when Receipt::READER_CANCELED
      "Canceled by reader"
    when Receipt::LIBRARIAN_CANCELED
      "Canceled by librarian"
    when Receipt::CANCELED_ACTIVE
      "Pending deletion"
    when Receipt::ACTIVE
      "In processing"
    when Receipt::READY
      "Ready to ship"
    when Receipt::SHIPPED
      "Shipped to reader"
    when Receipt::RETURNED
      "Returned by reader"
    else
       "NIEZNANY STATUS"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for @book, :html => { :class => 'form-horizontal' } do |f| %>
    <% if @book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@book.errors.count, "error") %> prohibited this entry from being saved:</h2>

          <ul>
            <% @book.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



    <div class="control-group">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :release_date, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :release_date, :class => 'text_field' %>
      </div>
      <div class="control-group">
        <%= f.label :release_date, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_area :release_date, :class => 'text_area' %>
        </div>
      </div>

      <div class="controls">
        <%= f.file_field :avatar, :class => 'file_field' %>
      </div>
    </div>
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/books/edit.html.erb
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<%- model_class = Book -%>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Books Index</div>
  <section class="books">
    <% @books.each do |book| %>
        <article class="book">

          <%= link_to "#{book.title}", book_path(book) %>
          <%= image_tag book.avatar.url(:thumb) %>

          <p><%= book.release_date %></p>

          <p>
            <% book.authors.each do |author| %>
                <%= author.name %><%= " " %><%= author.surname %>
            <% end %>
          </p>
          <% if reader_signed_in? %>
              <%= form_for Receipt.new do |f|%>
                <%= f.hidden_field :book_id, :value => book.id %>
                <%= f.submit "Order book", class: "btn btn-primary"  %>
              <% end %>

          <% elsif librarian_signed_in? %>
              <%= link_to "Edit", edit_book_path(book), class: "btn btn-primary" %>
              <%= link_to "Remove", book,
                            data: {confirm: 'Are you sure?', :method => :delete}, class: "btn btn-primary" %>

          <% end %>
        </article>
    <% end %>
  </section>
  <%= will_paginate @books %>
</div>

app/views/books/new.html.erb
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<section class ="book-parameters">
<h1><%= @book.title %></h1>
<%= image_tag @book.avatar.url %>
<h3>Release date: <%= @book.release_date %></h3>
</section>

<section class="book-description">

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biblioteka</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="wrapper">

  <div class="header">
  </div>

  <header class="navbar navbar-inverse bs-docs-nav" role="banner">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="../" class="navbar-brand">Bookstore.ly</a>
      </div>
      <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to "Books", books_path %>
          </li>
          <% if reader_signed_in? or librarian_signed_in? %>
              <li>
                <%= link_to "Receipts", receipts_path %>
              </li>
          <% end %>

        </ul>

        <ul class="nav navbar-nav navbar-right">

          <% if reader_signed_in? %>
              <li>
                <%= link_to "Sign out", destroy_reader_session_path, method: :delete %>
              </li>
          <% elsif librarian_signed_in? %>

              <li>
                <%= link_to "Add Book", new_book_path %>
              </li>
              <li>
                <%= link_to "Sign out", destroy_librarian_session_path, method: :delete %>
              </li>
          <% else %>
              <li>
                <%= link_to "Sign in", new_reader_session_path %>
              </li>
              <li>
                <%= link_to "Sign up", new_reader_registration_path %>
              </li>
          <% end %>


          </li>
        </ul>
      </nav>
    </div>
  </header>

  <% if (reader_signed_in? || librarian_signed_in?) %>
      <div class="logged pull-right">
        <% if librarian_signed_in? %>
            <div id= "libwelcome">Welcome, librarian <%= current_librarian.name %></div>
        <% end %>

        <% if reader_signed_in? %>
            <div id="readwelcome">Welcome, reader <%= current_reader.name %></div>
        <% end %>
      </div>
  <% end %>


  <% if flash[:alert] %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
  <% end %>
  <% if flash[:notice] %>
      <div class="alert alert-info"><%= flash[:notice] %></div>
  <% end %>

  <%= yield %>

  <div class="push"></div>

</div>

<div class="footer">
  <p class="copyright">Copyright &copy; 2013 Aleksandros Kifonidis &mdash; <a href="http://google.pl/" title="My CV">CV</a></p>
</div>

</body>

</html>

app/views/librarians/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/readers/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/receipts/_buttons.html.erb
<% if librarian_signed_in? %>
    <% if receipt.status == Receipt::NEW%>

        <%= button_to "ACCEPT RECEIPT", receipt, :name => "accepted", method: :patch %>
        <%= button_to "CANCEL RECEIPT", receipt, :name => "librarian_canceled", method: :patch %>
    <% end%>
<% end%>
<% if librarian_signed_in? && current_librarian == receipt.librarian%>
    <% if receipt.status == Receipt::CANCELED%>

    <% end%>
    <% if receipt.status == Receipt::ACTIVE%>

      <%= button_to "CANCEL RECEIPT", receipt, :name => "librarian_canceled", method: :patch %>
      <%= button_to "READY ORDER", receipt, :name => "ready", method: :patch %>
    <% end%>
    <% if receipt.status == Receipt::READY%>

      <%= button_to "CANCEL RECEIPT", receipt, :name => "librarian_canceled", method: :patch %>
      <%= button_to "SHIPPED", receipt, :name => "shipped", method: :patch %>
    <% end%>
    <% if receipt.status == Receipt::SHIPPED%>

        <%= button_to "RETURNED", receipt, :name => "returned", method: :patch %>
    <% end%>
    <% if receipt.status == Receipt::CANCELED_ACTIVE%>

       <%= button_to "CANCEL CHECKED", receipt, :name => "checked_canceled", method: :patch %>
    <% end%>
<% end%>

<% if current_reader == receipt.reader %>
    <% if receipt.status == Receipt::NEW%>

       <%=button_to "CANCEL", receipt, name: "reader_canceled", method: :patch %>
    <% end%>
    <% if receipt.status == Receipt::ACTIVE%>

        <%= button_to "CANCEL", receipt, name: "reader_canceled", method: :patch %>
    <% end%>
<% end %>

app/views/receipts/edit.html.erb
<%- model_class = Receipt -%>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Books Index</div>
  <section class="books">
    <% @books.each do |book| %>
        <article class="book">
          <h3><%= book.title %></h3>
          <%= image_tag book.avatar.url(:thumb) %>

          <p><%= book.release_date %></p>

          <p>
            <% book.authors.each do |author| %>
                <%= author.name %><%= " " %><%= author.surname %>
            <% end %>
          </p>
          <% if reader_signed_in? %>
              <%= link_to "Order book", create_receipt_path(book), class: "btn btn-primary" %>

          <% elsif librarian_signed_in? %>
              <%= link_to "Edit", edit_book_path(book), class: "btn btn-primary" %>
              <%= link_to "Remove", book,
                          data: {confirm: 'Are you sure?', :method => :delete}, class: "btn btn-primary" %>

          <% end %>
        </article>
    <% end %>
  </section>
  <%= will_paginate @books %>
</div>

app/views/receipts/index.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Receipts Index</div>

  <!-- Table -->
  <table class="table">
    <thead>
    <tr>
      <th>STATUS</th>
      <th>Title</th>
      <th>Authors</th>
      <th>Librarian</th>
      <th>ACTIONS</th>
    </tr>
    </thead>
    <tbody>
    <% @receipts.each do |receipt| %>
        <tr>
          <td><%= status_for(receipt)%></td>
          <td><%= receipt.book.title %></td>
          <td>
              <% receipt.book.authors.each do |author| %>
                <%= author.name%> <%= author.surname %>
              <% end %>
          </td>
          <td>
          <% if receipt.librarian %>
              <%= receipt.librarian.name %> <%= receipt.librarian.surname %>
          <% end %>
          </td>
          <td>
            <%= render :partial => "buttons", locals: {receipt: receipt}%>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
  </br>
  <%= will_paginate @receipts %>
</div>